default:
  suffix: !expr Sys.getenv("USER")
  schema: !expr Sys.getenv("SCHEMA")
  user: !expr Sys.getenv("DATABASE_USER_R")
  password: !expr Sys.getenv("DATABASE_PASSWORD_R")

production:
  suffix: "production"
  schema: "production"
  user: "captain_r"
  password: !expr Sys.getenv("CAPTAIN_R_PASSWORD")
